-- 002_schemas.down.sql
DROP SCHEMA IF EXISTS audit CASCADE;
DROP SCHEMA IF EXISTS search CASCADE;
DROP SCHEMA IF EXISTS identity CASCADE;
DROP SCHEMA IF EXISTS notifications CASCADE;
DROP SCHEMA IF EXISTS intelligence CASCADE;
DROP SCHEMA IF EXISTS evidence CASCADE;
DROP SCHEMA IF EXISTS documents CASCADE;
DROP SCHEMA IF EXISTS ingestion CASCADE;
DROP SCHEMA IF EXISTS legislation CASCADE;
