-- 003_kenya_stages.sql
-- Kenya Bill lifecycle stages, derived from the kenya.parliament adapter.
-- Each stage lists its allowed_next transitions. Idempotent via ON CONFLICT.

INSERT INTO legislation.bill_stages (country_id, stage_code, name, simple_explanation, allowed_next, sequence, is_terminal) VALUES
    ('KE', 'DRAFTED',                 'Drafted',
     'Bill has been drafted but not yet published.',
     '{"next":["PUBLICATION"],"is_terminal":false,"category":"pre_introduction"}'::jsonb,
     1, FALSE),
    ('KE', 'PUBLICATION',             'Publication',
     'Bill has been published in the Kenya Gazette.',
     '{"next":["FIRST_READING"],"is_terminal":false,"category":"introduction"}'::jsonb,
     2, FALSE),
    ('KE', 'FIRST_READING',           'First Reading',
     'Bill is read for the first time in the House; no debate on the merits.',
     '{"next":["SECOND_READING","WITHDRAWN"],"is_terminal":false,"category":"introduction"}'::jsonb,
     3, FALSE),
    ('KE', 'SECOND_READING',          'Second Reading',
     'House debates the principles and policies of the Bill.',
     '{"next":["COMMITTEE_STAGE","WITHDRAWN"],"is_terminal":false,"category":"consideration"}'::jsonb,
     4, FALSE),
    ('KE', 'COMMITTEE_STAGE',         'Committee Stage',
     'Bill is committed to a committee for clause-by-clause scrutiny and amendment.',
     '{"next":["REPORT_STAGE","WITHDRAWN"],"is_terminal":false,"category":"consideration"}'::jsonb,
     5, FALSE),
    ('KE', 'REPORT_STAGE',            'Report Stage',
     'Committee reports back to the House; further amendments are considered.',
     '{"next":["THIRD_READING","WITHDRAWN"],"is_terminal":false,"category":"consideration"}'::jsonb,
     6, FALSE),
    ('KE', 'THIRD_READING',           'Third Reading',
     'Bill is read a third time; final debate before voting.',
     '{"next":["PASSED","WITHDRAWN"],"is_terminal":false,"category":"consideration"}'::jsonb,
     7, FALSE),
    ('KE', 'PASSED',                  'Passed',
     'Bill has been passed by the originating House and (for bicameral Bills) mediated between Houses.',
     '{"next":["ASSENT"],"is_terminal":false,"category":"post_consideration"}'::jsonb,
     8, FALSE),
    ('KE', 'ASSENT',                  'Presidential Assent',
     'Bill is presented to the President for assent.',
     '{"next":["COMMENCEMENT","REFERRED_BACK"],"is_terminal":false,"category":"post_consideration"}'::jsonb,
     9, FALSE),
    ('KE', 'REFERRED_BACK',          'Referred Back by President',
     'President has referred the Bill back to Parliament with proposed amendments or reservations.',
     '{"next":["ASSENT","REJECTED"],"is_terminal":false,"category":"post_consideration"}'::jsonb,
     10, FALSE),
    ('KE', 'COMMENCEMENT',            'Commencement',
     'Act comes into force on the date specified in the Act or by legal notice.',
     '{"next":[],"is_terminal":true,"category":"enacted"}'::jsonb,
     11, TRUE),
    ('KE', 'REJECTED',                'Rejected',
     'Bill has been rejected (either by the House or by presidential refusal of assent after re-presentation).',
     '{"next":[],"is_terminal":true,"category":"terminal"}'::jsonb,
     12, TRUE),
    ('KE', 'WITHDRAWN',               'Withdrawn',
     'Bill has been withdrawn by the sponsor.',
     '{"next":[],"is_terminal":true,"category":"terminal"}'::jsonb,
     13, TRUE),
    ('KE', 'STALLED',                  'Stalled',
     'Bill has not progressed for two consecutive sitting sessions.',
     '{"next":["FIRST_READING","SECOND_READING","COMMITTEE_STAGE","REPORT_STAGE","THIRD_READING","WITHDRAWN"],
       "is_terminal":false,"category":"lapsed"}'::jsonb,
     14, FALSE)
ON CONFLICT (country_id, stage_code) DO UPDATE
    SET name = EXCLUDED.name,
        simple_explanation = EXCLUDED.simple_explanation,
        allowed_next = EXCLUDED.allowed_next,
        sequence = EXCLUDED.sequence,
        is_terminal = EXCLUDED.is_terminal;
