import type { Guide } from './types';

/**
 * Guide 4 of 5 — Your constitutional rights.
 *
 * Surfaces key articles from the 2010 Constitution (the Bill of Rights,
 * Chapter 4) and pairs each with a plain-language AI explanation. The
 * article text is FACT (verbatim from kenyalaw.org); the explanation
 * is EXPLANATION (AI-generated, citation-validated, clearly labelled).
 *
 * The RealityBadge pattern (FACT vs. EXPLANATION) follows the
 * platform-wide convention from `components/reality-labels.tsx` — the
 * same visual language used on /scenarios, /bills, and /constitution.
 */
export const yourConstitutionalRights: Guide = {
  slug: 'your-constitutional-rights',
  title: 'Your constitutional rights',
  summary:
    'Key articles from the Bill of Rights in the Constitution of Kenya, 2010 — each paired with a plain-language AI explanation.',
  description:
    'A plain-language guide to the Bill of Rights in the Constitution of Kenya, 2010 — Articles 19, 26, 27, 28, 31, 33, 35, 43, 46, and 50 — each with the constitutional text and an AI explanation.',
  category: 'Constitution',
  readingTimeMinutes: 10,
  lastReviewed: '2025-01-15',
  sources: [
    {
      label: 'Constitution of Kenya, 2010 — Chapter 4 (The Bill of Rights)',
      url: 'https://www.kenyalaw.org/kl/index.php?id=398',
    },
    {
      label: 'Kenya National Commission on Human Rights',
      url: 'https://www.knchr.org/',
    },
    {
      label: 'Read the Constitution on this platform',
      url: '/constitution',
    },
  ],
  relatedLinks: [
    {
      label: 'The Constitution, article by article',
      href: '/constitution',
      description: 'Browse every article of the Constitution with the original kenyalaw.org text.',
    },
    {
      label: 'How a Bill becomes a law',
      href: '/learn/how-a-bill-becomes-law',
      description: 'A Constitutional Amendment Bill needs a supermajority — see how in Guide 1.',
    },
    {
      label: 'Ask a civic question',
      href: '/ask',
      description: 'The AI grounds every answer in the constitutional text and cites its sources.',
    },
  ],
  sections: [
    {
      id: 'introduction',
      title: 'What the Bill of Rights is',
      body: (
        <>
          <p>
            The Bill of Rights is <strong>Chapter 4</strong> of the
            Constitution of Kenya, 2010 (Articles 19 to 59). It is the part
            of the Constitution that protects the freedoms and entitlements
            of every person in Kenya — citizens and non-citizens alike.
          </p>
          <p>
            The Bill of Rights is the framework for social, economic, and
            cultural policy: every law, every state action, and every
            government programme must be measured against it. A law that
            unconstitutionally limits a right is invalid to the extent of the
            inconsistency.
          </p>
          <p>
            Each section below shows the <strong>constitutional text</strong>{' '}
            (a verbatim quote from kenyalaw.org — a <em>FACT</em>), followed
            by a <strong>plain-language explanation</strong> generated by the
            platform&rsquo;s AI and citation-validated (an{' '}
            <em>EXPLANATION</em>).
          </p>
        </>
      ),
    },
    {
      id: 'article-19',
      title: 'Article 19 — Rights and Fundamental Freedoms',
      body: (
        <>
          <p>
            <strong>Constitutional text (FACT):</strong> &ldquo;The Bill of
            Rights is an integral part of Kenya&rsquo;s democratic State and
            is the framework for social, economic and cultural policies. The
            purpose of recognising and protecting rights and fundamental
            freedoms is to preserve the dignity of individuals and communities
            and to promote social justice and the realisation of the potential
            of all human beings.&rdquo;
          </p>
          <p>
            <strong>AI explanation (EXPLANATION):</strong> Article 19 tells
            us the Bill of Rights is not just a list of freedoms — it is the
            lens through which the State must design every policy. When the
            government drafts a budget, a Bill, or a regulation, it must
            justify how that policy preserves human dignity. This is why a
            court can strike down a law even if no individual was harmed: the
            test is whether the law itself is consistent with the Bill of
            Rights.
          </p>
          <p>
            Read the full article on the{' '}
            <a href="/constitution">Constitution page</a>.
          </p>
        </>
      ),
    },
    {
      id: 'article-26',
      title: 'Article 26 — Right to Life',
      body: (
        <>
          <p>
            <strong>Constitutional text (FACT):</strong> &ldquo;Every person
            has the right to life. The life of a person begins at conception.
            A person shall not be deprived of life intentionally, except to
            the extent authorised by this Constitution or other written
            law.&rdquo;
          </p>
          <p>
            <strong>AI explanation (EXPLANATION):</strong> Article 26 is one
            of the most-cited articles in Kenyan litigation. Two elements
            deserve attention. First, the Constitution expressly says life
            begins at conception — a phrase that has been the basis of much
            litigation around abortion law (Article 26(4) permits abortion
            only when, in the opinion of a trained health professional, the
            mother&rsquo;s life or health is in danger). Second, the State may
            not take life except as the Constitution itself authorises —
            meaning the death penalty, while on the statute books, is
            constrained by this article.
          </p>
        </>
      ),
    },
    {
      id: 'article-27',
      title: 'Article 27 — Equality and Freedom from Discrimination',
      body: (
        <>
          <p>
            <strong>Constitutional text (FACT):</strong> &ldquo;Every person
            is equal before the law and has the right to equal protection and
            equal benefit of the law. Equality includes the full and equal
            enjoyment of all rights and fundamental freedoms. The State shall
            not discriminate directly or indirectly against any person on any
            ground, including race, sex, pregnancy, marital status, health
            status, ethnic or social origin, colour, age, disability,
            religion, conscience, belief, culture, dress, language or
            birth.&rdquo;
          </p>
          <p>
            <strong>AI explanation (EXPLANATION):</strong> Article 27 lists
            the protected grounds of non-discrimination. Two features make
            this article unusually powerful. First, the list is
            non-exhaustive (&ldquo;including&rdquo;) — courts can recognise
            new grounds. Second, both <em>direct</em> and{' '}
            <em>indirect</em> discrimination are prohibited: a rule that
            looks neutral on its face but disadvantages a protected group in
            practice is also unconstitutional. Article 27(8) further requires
            the State to take legislative and other measures to ensure that
            not more than two-thirds of elective bodies are of the same
            gender — the &ldquo;two-thirds gender rule&rdquo;.
          </p>
        </>
      ),
    },
    {
      id: 'article-28',
      title: 'Article 28 — Human Dignity',
      body: (
        <>
          <p>
            <strong>Constitutional text (FACT):</strong> &ldquo;Every person
            has inherent dignity and the right to have that dignity respected
            and protected.&rdquo;
          </p>
          <p>
            <strong>AI explanation (EXPLANATION):</strong> Article 28 is the
            shortest article in the Bill of Rights and one of the most
            consequential. Dignity is treated as inherent — meaning it is
            not granted by the State and cannot be taken away. Courts have
            used Article 28 to limit police powers (e.g. to prohibit
            degrading treatment of detainees), to require humane conditions
            in prisons, and to ground the right to a name and identity.
            Article 28 also underpins Article 19: the entire purpose of the
            Bill of Rights is to preserve human dignity.
          </p>
        </>
      ),
    },
    {
      id: 'article-31',
      title: 'Article 31 — Privacy',
      body: (
        <>
          <p>
            <strong>Constitutional text (FACT):</strong> &ldquo;Every person
            has the right to privacy, which includes the right not to have
            their person, home or property searched; their possessions seized;
            information relating to their family or private affairs
            unnecessarily required or revealed; or the privacy of their
            communications infringed.&rdquo;
          </p>
          <p>
            <strong>AI explanation (EXPLANATION):</strong> Article 31 is the
            constitutional foundation of data-protection law in Kenya. The
            Data Protection Act, 2019 (which you can browse on the{' '}
            <a href="/acts">Acts page</a>) gives effect to this article by
            setting out how organisations may collect, store, and process
            personal data. Article 31 also constrains State surveillance: the
            police cannot search a home, seize property, or intercept
            communications without legal authority (typically a court order).
          </p>
        </>
      ),
    },
    {
      id: 'article-33',
      title: 'Article 33 — Freedom of Expression',
      body: (
        <>
          <p>
            <strong>Constitutional text (FACT):</strong> &ldquo;Every person
            has the right to freedom of expression, which includes freedom
            to seek, receive or impart information or ideas; freedom of
            artistic creativity; and academic freedom and freedom of
            scientific research.&rdquo;
          </p>
          <p>
            <strong>AI explanation (EXPLANATION):</strong> Article 33
            protects expression in three forms — seeking, receiving, and
            imparting information — across all media. The right is not
            absolute: Article 33(2) permits limitations for propaganda for
            war, incitement to violence, hate speech, and advocacy of hatred.
            The Supreme Court has held that the burden of justifying any
            limitation on free expression falls on the State, and the
            limitation must be proportionate. This article is the basis for
            press freedom in Kenya and is invoked in challenges to media
            regulations and content takedown orders.
          </p>
        </>
      ),
    },
    {
      id: 'article-35',
      title: 'Article 35 — Access to Information',
      body: (
        <>
          <p>
            <strong>Constitutional text (FACT):</strong> &ldquo;Every citizen
            has the right to access information held by the State; and
            information held by another person and required for the exercise
            or protection of any right.&rdquo;
          </p>
          <p>
            <strong>AI explanation (EXPLANATION):</strong> Article 35 is the
            backbone of the platform you are reading right now. The
            Constitution obliges the State to publish and publicise any
            important information affecting the nation. The Access to
            Information Act, 2016 operationalises this right — citizens can
            request information from any public body, and the body must
            respond within 21 days. This is also why official sources (like
            kenyalaw.org and parliament.go.ke) are the foundation of every
            claim this platform surfaces.
          </p>
        </>
      ),
    },
    {
      id: 'article-43',
      title: 'Article 43 — Economic and Social Rights',
      body: (
        <>
          <p>
            <strong>Constitutional text (FACT):</strong> &ldquo;Every person
            has the right to the highest attainable standard of health;
            accessible and adequate housing and to reasonable standards of
            sanitation; to be free from hunger, and to have adequate food of
            acceptable quality; to clean and safe water in adequate quantities;
            to social security; and to education.&rdquo;
          </p>
          <p>
            <strong>AI explanation (EXPLANATION):</strong> Article 43 protects
            &ldquo;positive&rdquo; rights — things the State must{' '}
            <em>do</em> (provide health, housing, food, water, social
            security, education) rather than merely refrain from interfering
            with. These rights are subject to progressive realisation
            (Article 21(2)): the State must take steps &ldquo;to the maximum
            of available resources&rdquo;. This makes Article 43 harder to
            enforce in court than the civil-political rights above, but it
            anchors every budget debate — including the housing levy
            litigation that reached the Court of Appeal and the High Court.
          </p>
        </>
      ),
    },
    {
      id: 'article-46',
      title: 'Article 46 — Consumer Rights',
      body: (
        <>
          <p>
            <strong>Constitutional text (FACT):</strong> &ldquo;Consumers have
            the right to goods and services of reasonable quality; to the
            information necessary for them to gain full benefit from goods
            and services; to the protection of their health, safety and
            economic interests; and to compensation for loss or injury
            arising from defects in goods or services.&rdquo;
          </p>
          <p>
            <strong>AI explanation (EXPLANATION):</strong> Article 46
            constitutionalises consumer protection — previously a matter of
            statute alone. The Consumer Protection Act, 2012 gives effect to
            this article. Article 46 has been invoked in challenges to
            misleading advertising, unsafe products, and unfair contract
            terms. It also entitles consumers to compensation for defective
            goods, which strengthens the remedies available under ordinary
            contract and tort law.
          </p>
        </>
      ),
    },
    {
      id: 'article-50',
      title: 'Article 50 — Fair Hearing',
      body: (
        <>
          <p>
            <strong>Constitutional text (FACT):</strong> &ldquo;Every person
            has the right to have any dispute that can be resolved by the
            application of law decided in a fair and public hearing before a
            court or, where appropriate, another independent and impartial
            tribunal or body.&rdquo;
          </p>
          <p>
            <strong>AI explanation (EXPLANATION):</strong> Article 50 is the
            constitutional source of due-process rights in Kenya: the right
            to be informed of the charge, to be presumed innocent, to be
            tried in public, to have adequate time and facilities to prepare
            a defence, to call and cross-examine witnesses, and to be
            represented by a lawyer of one&rsquo;s choice. Article 50(2)
            enumerates the rights of an accused person in a criminal trial;
            Article 50(1) is broader, applying to <em>any</em> justiciable
            dispute. A court that violates Article 50 renders its decision
            voidable on appeal.
          </p>
        </>
      ),
    },
    {
      id: 'limits-and-enforcement',
      title: 'Limits, duties, and enforcement',
      body: (
        <>
          <h3>Rights are not absolute — but limits must be justified</h3>
          <p>
            Article 24 permits the State to limit a right only if the
            limitation is &ldquo;reasonable and justifiable in an open and
            democratic society based on human dignity, equality and
            freedom&rdquo;. The State carries the burden of proving that a
            limitation meets this test.
          </p>
          <h3>The State has a duty to realise rights</h3>
          <p>
            Article 21 imposes a fundamental duty on the State and every
            State organ to observe, respect, protect, promote, and fulfil
            the rights in the Bill of Rights. &ldquo;Fulfil&rdquo; means the
            State must take positive steps to realise rights — not merely
            refrain from violating them.
          </p>
          <h3>Enforcement — the High Court</h3>
          <p>
            Article 23 gives the High Court jurisdiction to hear matters
            alleging a right has been denied, violated, infringed, or
            threatened. The court may award compensation, declare a law
            unconstitutional, or order the State to take action. Article 22
            further provides that <em>any person</em> — not only the victim
            — may institute court proceedings to enforce the Bill of Rights.
          </p>
          <p>
            Read all 59 articles of the Bill of Rights on the{' '}
            <a href="/constitution">Constitution page</a>.
          </p>
        </>
      ),
    },
  ],
};
