package domain

import (
	"context"
	"fmt"
	"time"

	"github.com/Roy-Wanyoike/civic-intelligence/packages/contracts"
)

// CreateBillCommand is the input to create a new canonical Bill. The ID is
// generated by the repository (or supplied for testing).
type CreateBillCommand struct {
	CountryID    contracts.Country
	HouseID      contracts.ID
	Identifier   string
	Year         int
	Title        string
	SponsorID    *contracts.ID
	CommitteeID  *contracts.ID
	Purpose      string
	Description  string
	Topics       []string
}

// CreateBill is the use case that creates a new Bill. It enforces uniqueness
// (country + identifier + year) and emits a bill.discovered event.
type CreateBill struct {
	repos    BillRepository
	eventPub EventPublisher
}

// EventPublisher is the abstraction for publishing domain events (NATS in prod).
// Tests use an in-memory implementation.
type EventPublisher interface {
	Publish(ctx context.Context, et contracts.EventType, payload map[string]any) error
}

func NewCreateBill(repos BillRepository, pub EventPublisher) *CreateBill {
	return &CreateBill{repos: repos, eventPub: pub}
}

func (uc *CreateBill) Execute(ctx context.Context, cmd CreateBillCommand) (*Bill, error) {
	// Idempotency: if a Bill with this (country, identifier, year) already exists,
	// return it instead of creating a duplicate.
	if existing, err := uc.repos.FindByIdentifier(ctx, cmd.CountryID, cmd.Identifier, cmd.Year); err == nil && existing != nil {
		return existing, nil
	}

	bill := &Bill{
		CountryID:   cmd.CountryID,
		HouseID:     cmd.HouseID,
		Identifier:  cmd.Identifier,
		Year:        cmd.Year,
		Title:       cmd.Title,
		SponsorID:   cmd.SponsorID,
		CommitteeID: cmd.CommitteeID,
		Status:      BillStatusInProgress,
		Purpose:     cmd.Purpose,
		Description: cmd.Description,
		Topics:      cmd.Topics,
		CreatedAt:   time.Now().UTC(),
		UpdatedAt:   time.Now().UTC(),
	}

	if err := uc.repos.Save(ctx, bill); err != nil {
		return nil, fmt.Errorf("save bill: %w", err)
	}

	_ = uc.eventPub.Publish(ctx, contracts.EventBillDiscovered, map[string]any{
		"bill_id":    string(bill.ID),
		"country":    string(bill.CountryID),
		"identifier": bill.Identifier,
		"title":      bill.Title,
	})

	return bill, nil
}
