// In production, this data comes from the Go BFF which reads from Postgres.
// Until ingestion runs, we ship a small set of illustrative Bills that
// represent the shape of real Kenyan legislation. All facts shown here are
// PUBLIC and well-known — they are placeholders for the ingestion pipeline.

import type { Bill, BillEvent, DailyBriefing } from './types';

export const mockBills: Bill[] = [
  {
    id: '00000000-0000-0000-0000-000000000001',
    identifier: 'NA Bill No. 23',
    title: 'The Housing Bill, 2024',
    year: 2024,
    sponsor_id: null,
    sponsor_name: 'Cabinet Secretary, Lands',
    house_id: null,
    house_name: 'National Assembly',
    committee_id: null,
    committee_name: 'Departmental Committee on Lands',
    status: 'in_progress',
    current_stage: 'Committee Stage',
    current_stage_simple_explanation:
      'The Bill is being examined clause-by-clause by a parliamentary committee before it returns to the House for Report Stage.',
    purpose:
      'To provide a framework for affordable housing, including the establishment of a Housing Fund and the regulation of housing development.',
    description:
      'This Bill would establish the legal framework for affordable housing programmes in Kenya, including a Housing Fund financed through contributions and the regulation of housing development.',
    country: 'KE',
    created_at: '2024-03-15T09:00:00Z',
    updated_at: '2024-09-08T14:30:00Z',
    citation_count: 12,
    version_count: 3,
    event_count: 8,
    topics: ['housing', 'public-finance'],
  },
  {
    id: '00000000-0000-0000-0000-000000000002',
    identifier: 'Senate Bill No. 11',
    title: 'The Data Protection (Amendment) Bill, 2024',
    year: 2024,
    sponsor_id: null,
    sponsor_name: 'Senator, Committee on ICT',
    house_id: null,
    house_name: 'Senate',
    committee_id: null,
    committee_name: 'Standing Committee on Information, Communication and Technology',
    status: 'in_progress',
    current_stage: 'Second Reading',
    current_stage_simple_explanation:
      'The Bill is being debated at the level of principles. MPs are discussing whether the Bill should proceed at all.',
    purpose:
      'To amend the Data Protection Act, 2019 to strengthen citizen data rights and update cross-border data transfer rules.',
    description:
      'This Bill would update Kenya\'s 2019 data protection law to address new uses of personal data, including AI training data and cross-border transfers.',
    country: 'KE',
    created_at: '2024-05-20T10:00:00Z',
    updated_at: '2024-09-07T11:15:00Z',
    citation_count: 24,
    version_count: 2,
    event_count: 5,
    topics: ['data-protection', 'ict'],
  },
  {
    id: '00000000-0000-0000-0000-000000000003',
    identifier: 'NA Bill No. 41',
    title: 'The Public Finance Management (Amendment) Bill, 2024',
    year: 2024,
    sponsor_id: null,
    sponsor_name: 'Cabinet Secretary, National Treasury',
    house_id: null,
    house_name: 'National Assembly',
    committee_id: null,
    committee_name: 'Departmental Committee on Finance and National Planning',
    status: 'in_progress',
    current_stage: 'First Reading',
    current_stage_simple_explanation:
      'The Bill has been introduced and read for the first time. It has not yet been debated.',
    purpose:
      'To amend the Public Finance Management Act, 2015 to update budget formulation timelines and strengthen oversight of public debt.',
    description:
      'This Bill would tighten timelines for budget submission and introduce new reporting requirements for public debt.',
    country: 'KE',
    created_at: '2024-08-01T09:00:00Z',
    updated_at: '2024-09-06T16:00:00Z',
    citation_count: 8,
    version_count: 1,
    event_count: 3,
    topics: ['public-finance', 'taxation'],
  },
  {
    id: '00000000-0000-0000-0000-000000000004',
    identifier: 'NA Bill No. 12',
    title: 'The Traffic (Amendment) Bill, 2024',
    year: 2024,
    sponsor_id: null,
    sponsor_name: 'Member of Parliament',
    house_id: null,
    house_name: 'National Assembly',
    committee_id: null,
    committee_name: 'Departmental Committee on Transport, Public Works and Housing',
    status: 'enacted',
    current_stage: 'Commencement',
    current_stage_simple_explanation:
      'The Bill has been assented to by the President and is now law. It is awaiting commencement.',
    purpose:
      'To amend the Traffic Act to update penalties for traffic offences and introduce mandatory retesting of drivers.',
    description:
      'This Bill updated penalties under the Traffic Act and introduced mandatory retesting for commercial drivers.',
    country: 'KE',
    created_at: '2024-01-15T09:00:00Z',
    updated_at: '2024-09-01T10:00:00Z',
    citation_count: 16,
    version_count: 4,
    event_count: 12,
    topics: ['transport', 'security'],
  },
  {
    id: '00000000-0000-0000-0000-000000000005',
    identifier: 'Senate Bill No. 7',
    title: 'The County Government (Amendment) Bill, 2024',
    year: 2024,
    sponsor_id: null,
    sponsor_name: 'Senator',
    house_id: null,
    house_name: 'Senate',
    committee_id: null,
    committee_name: 'Standing Committee on Finance and Budget',
    status: 'in_progress',
    current_stage: 'Committee of the Whole House',
    current_stage_simple_explanation:
      'The Bill is being examined clause-by-clause by the whole House, not just a committee.',
    purpose:
      'To amend the County Governments Act to update the framework for county budgeting and inter-governmental fiscal relations.',
    description:
      'This Bill would change how counties prepare and submit budgets and how disputes with the national government are resolved.',
    country: 'KE',
    created_at: '2024-04-10T09:00:00Z',
    updated_at: '2024-09-05T15:30:00Z',
    citation_count: 9,
    version_count: 2,
    event_count: 6,
    topics: ['county-government', 'public-finance'],
  },
  {
    id: '00000000-0000-0000-0000-000000000006',
    identifier: 'NA Bill No. 30',
    title: 'The Education (Amendment) Bill, 2024',
    year: 2024,
    sponsor_id: null,
    sponsor_name: 'Cabinet Secretary, Education',
    house_id: null,
    house_name: 'National Assembly',
    committee_id: null,
    committee_name: 'Departmental Committee on Education and Research',
    status: 'in_progress',
    current_stage: 'Second Reading',
    current_stage_simple_explanation:
      'The Bill is being debated at the level of principles.',
    purpose:
      'To amend the Basic Education Act to align with the Competency-Based Curriculum (CBC) and update junior school transition rules.',
    description:
      'This Bill would align basic education law with the CBC reforms and clarify the transition from junior to senior school.',
    country: 'KE',
    created_at: '2024-06-01T09:00:00Z',
    updated_at: '2024-09-04T12:00:00Z',
    citation_count: 14,
    version_count: 2,
    event_count: 7,
    topics: ['education'],
  },
];

export const mockTimeline: BillEvent[] = [
  {
    id: 'ev-1',
    bill_id: '00000000-0000-0000-0000-000000000001',
    event_type: 'first_reading',
    date: '2024-03-20T10:00:00Z',
    date_is_approximate: false,
    house: 'National Assembly',
    description: 'Bill read for the first time in the National Assembly.',
    source_url: 'https://parliament.go.ke/bills/2024/housing',
    confidence: 'high',
    note: null,
  },
  {
    id: 'ev-2',
    bill_id: '00000000-0000-0000-0000-000000000001',
    event_type: 'first_reading',
    date: '2024-03-21T00:00:00Z',
    date_is_approximate: true,
    house: 'National Assembly',
    description: 'Bill committed to the Departmental Committee on Lands for consideration.',
    source_url: 'https://parliament.go.ke/bills/2024/housing',
    confidence: 'high',
    note: 'Exact date inferred from Order Paper; precise committee referral date not explicitly stated.',
  },
  {
    id: 'ev-3',
    bill_id: '00000000-0000-0000-0000-000000000001',
    event_type: 'public_participation',
    date: '2024-05-15T00:00:00Z',
    date_is_approximate: false,
    house: 'National Assembly',
    description: 'Committee published a call for public submissions.',
    source_url: 'https://parliament.go.ke/committees/lands',
    confidence: 'high',
    note: null,
  },
  {
    id: 'ev-4',
    bill_id: '00000000-0000-0000-0000-000000000001',
    event_type: 'committee_consideration',
    date: '2024-07-02T00:00:00Z',
    date_is_approximate: false,
    house: 'National Assembly',
    description: 'Committee began clause-by-clause consideration of the Bill.',
    source_url: 'https://parliament.go.ke/committees/lands',
    confidence: 'high',
    note: null,
  },
  {
    id: 'ev-5',
    bill_id: '00000000-0000-0000-0000-000000000001',
    event_type: 'version_published',
    date: '2024-09-08T00:00:00Z',
    date_is_approximate: false,
    house: 'National Assembly',
    description: 'Committee published a revised version of the Bill incorporating proposed amendments.',
    source_url: 'https://parliament.go.ke/bills/2024/housing/v3',
    confidence: 'high',
    note: null,
  },
];

export const mockBriefing: DailyBriefing = {
  country: 'KE',
  date: new Date().toISOString(),
  headline: 'Kenya Civic Brief — 3 verified developments today.',
  items: [
    {
      kind: 'new_document',
      title: 'Housing Bill, 2024 — revised version published',
      description:
        'The Departmental Committee on Lands published a revised version of the Housing Bill incorporating proposed amendments following public participation.',
      bill_id: '00000000-0000-0000-0000-000000000001',
      citations: [
        {
          document_id: 'doc-1',
          source_url: 'https://parliament.go.ke/bills/2024/housing/v3',
          page_number: 1,
          section: 'Order Paper',
          snippet:
            'The Departmental Committee on Lands published a revised version of the Housing Bill, 2024 on 8 September 2024.',
          source_type: 'order_paper',
          retrieved_at: new Date().toISOString(),
        },
      ],
      significance: 'A Bill has advanced; a revised text is now available for review before Report Stage.',
      confidence: 'high',
    },
    {
      kind: 'stage_change',
      title: 'Data Protection (Amendment) Bill — Second Reading continues',
      description:
        'The Senate continued debate on the Data Protection (Amendment) Bill at Second Reading.',
      bill_id: '00000000-0000-0000-0000-000000000002',
      citations: [
        {
          document_id: 'doc-2',
          source_url: 'https://senate.go.ke/hansard/2024-09-07',
          page_number: 4,
          section: 'Hansard',
          snippet:
            'The Senate resumed debate on the Second Reading of the Data Protection (Amendment) Bill, 2024.',
          source_type: 'hansard',
          retrieved_at: new Date().toISOString(),
        },
      ],
      significance: 'A Bill is being actively debated; final vote on principles may follow.',
      confidence: 'high',
    },
    {
      kind: 'new_bill',
      title: 'Public Finance Management (Amendment) Bill, 2024 introduced',
      description:
        'A new Bill was read for the first time in the National Assembly.',
      bill_id: '00000000-0000-0000-0000-000000000003',
      citations: [
        {
          document_id: 'doc-3',
          source_url: 'https://parliament.go.ke/bills/2024/pfm-amendment',
          page_number: 2,
          section: 'Order Paper',
          snippet: 'The Public Finance Management (Amendment) Bill, 2024 was read a first time.',
          source_type: 'order_paper',
          retrieved_at: new Date().toISOString(),
        },
      ],
      significance: 'A new Bill has entered the legislative process.',
      confidence: 'high',
    },
  ],
  generated_at: new Date().toISOString(),
};
